-- MySQL Script generated by MySQL Workbench
-- Thu Aug  1 14:26:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  `Phone` VARCHAR(15) NULL,
  `Email` VARCHAR(45) NULL,
  `Customercol` VARCHAR(100) NULL,
  `Address` VARCHAR(255) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Boat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Boat` (
  `BoatID` INT NOT NULL AUTO_INCREMENT,
  `CustomerID` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Type` VARCHAR(45) NULL,
  `Length` DECIMAL(5,2) NULL,
  `year` YEAR NULL,
  PRIMARY KEY (`BoatID`),
  INDEX `CustomerID_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Boat_Customer`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service` (
  `ServiceID` INT NOT NULL AUTO_INCREMENT,
  `BoatID` INT NOT NULL,
  `ServiceType` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Cost` DECIMAL(10,2) NULL,
  PRIMARY KEY (`ServiceID`),
  INDEX `fk_Service_Boat_idx` (`BoatID` ASC) VISIBLE,
  CONSTRAINT `fk_Service_Boat`
    FOREIGN KEY (`BoatID`)
    REFERENCES `mydb`.`Boat` (`BoatID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Boatyard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Boatyard` (
  `BoatyardID` INT NOT NULL AUTO_INCREMENT,
  `Location` VARCHAR(100) NULL,
  `Capacity` INT NULL,
  `BoatID` INT NULL,
  `NoOfStaff` INT NULL,
  PRIMARY KEY (`BoatyardID`),
  INDEX `fk_Boatyard_boat_idx` (`BoatID` ASC) VISIBLE,
  CONSTRAINT `fk_Boatyard_boat`
    FOREIGN KEY (`BoatID`)
    REFERENCES `mydb`.`Boat` (`BoatID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `StaffID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  `Role` VARCHAR(50) NULL,
  `Phone` VARCHAR(15) NULL,
  `Email` VARCHAR(100) NULL,
  `DateOfBirth` DATE NULL,
  `ContactNo` VARCHAR(45) NULL,
  `BoatyardID` INT NULL,
  PRIMARY KEY (`StaffID`),
  INDEX `fk_staff_Boatyard_idx` (`BoatyardID` ASC) VISIBLE,
  CONSTRAINT `fk_staff_Boatyard`
    FOREIGN KEY (`BoatyardID`)
    REFERENCES `mydb`.`Boatyard` (`BoatyardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServiceStaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ServiceStaff` (
  `ServiceID` INT NOT NULL,
  `StaffID` INT NOT NULL,
  `RoleInService` VARCHAR(45) NULL,
  INDEX `fk_ServiceStaff_Staff_idx` (`StaffID` ASC) VISIBLE,
  CONSTRAINT `fk_ServiceStaff_Service`
    FOREIGN KEY (`ServiceID`)
    REFERENCES `mydb`.`Service` (`ServiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServiceStaff_Staff`
    FOREIGN KEY (`StaffID`)
    REFERENCES `mydb`.`Staff` (`StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
